//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Name")]
        [RegularExpression(@"^[A-Z]{1}[a-z]+$", ErrorMessage = "First letter should be capital")]
        public string Username { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("E-mail")]

        public string Email { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Phone Number must 10 digits")]
        [DisplayName("PhoneNumber")]
        public string PhoneNumber { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Password")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm Password doesn't match")]
        [DisplayName("ConfirmPassword")]
        public string Confirmpassword { get; set; }

        public virtual Order Order { get; set; }
    }
}
